name: Keep repository active

on:
  schedule:
    - cron: "0 */12 * * *"   # toutes les 12h
  workflow_dispatch:

jobs:
  keepalive-job:
    runs-on: ubuntu-latest

    steps:
      - name: Simple keep-alive ping
        run: echo "Keepalive run at $(date)"
